name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.5.3
  latlong2: ^0.9.1
  http: ^1.6.0
  provider: ^6.1.5+1
  geolocator: ^14.0.2 # Reverted to ^12.0.0 as ^14.0.0 is not yet stable/available in common repos
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  device_preview: ^1.2.0
  image_picker: ^1.1.2
  esewa_flutter: ^3.0.1
  flutter_inappwebview: ^6.1.5
  crypto: ^3.0.6
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0
  
  # Firebase dependencies for push notifications
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2
  flutter_local_notifications: ^20.1.0
  
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/DOOKO.png
  android_12:
    image: assets/DOOKO.png
    ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/crop.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_banner.jpeg
    - assets/new_logowithGPS.jpeg
    - assets/farmers_market.jpeg
    - assets/app_logo.jpeg
    - assets/logo.png
    - assets/final_logo.png
    - assets/crop.png
